apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ilkai/devopsuserm:latest 
        ports:
        - containerPort: 3000
        env:
          - name: MYSQL_HOST
            value: test
          - name: MYSQL_PORT
            value: '3306'
          - name: MYSQL_USER
            value: root
          - name: MYSQL_ROOT_PASSWORD
            value: YXBpVXNlckEyMzEh
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer 

