apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: demo
  namespace: kasten-io
spec:
  comment: ""
  frequency: "@daily"
  paused: false
  actions:
    - action: backup
    - action: export
      exportParameters:
        frequency: "@daily"
        migrationToken:
          name: ""
          namespace: ""
        profile:
          name: export
          namespace: kasten-io
        receiveString: ""
        exportData:
          enabled: true
      retention:
        daily: 0
        weekly: 0
        monthly: 0
        yearly: 0
  retention:
    daily: 7
    weekly: 4
    monthly: 12
    yearly: 7
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - default
