apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      containers:
        - name: mysql
          image: ilkai/mysql-database:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_USER
              value: "ilkay"
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: "test"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  template:
    spec:
      initContainers:
      - name: init-mysql
        image: mysql:5.7
        command: ["sh", "-c", "mysql -h mysql-service -u root -proot_password < /docker-entrypoint-initdb.d/init.sql"]
        volumeMounts:
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root_password
        ports:
          - containerPort: 3306
      volumes:
      - name: init-scripts
        emptyDir: {}
