apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: ilkai/mysql-database:latest # MySQL Docker görüntüsü
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234" # MySQL root şifresini buraya ekleyin
            - name: MYSQL_DATABASE
              value: test # Kullanmak istediğiniz veritabanının adını buraya ekleyin
            - name: MYSQL_USER
              value: ilkay # Uygulamanızın kullanacağı MySQL kullanıcı adını buraya ekleyin
            - name: MYSQL_PASSWORD
              value: "1234" # Uygulamanızın kullanacağı MySQL şifresini buraya ekleyin
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP # İhtiyaca bağlı olarak değiştirilebilir
