---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: expressjs
  namespace: default
  labels:
    app: expressjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressjs
  template:
    metadata:
      labels:
        app: expressjs
    spec:
      containers:
      - name: expressjs
        image: ilkai/devopsuserm:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: expressjs
  namespace: default
spec:
  selector:
    app: expressjs
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: LoadBalancer
---
